# ！！！注意缩进，冒号后一定有空格！！！

#### server setting ################################################################################
server:
  context-path: /
  port: 9081

logging:
  config: classpath:logback-spring.xml
  path: /logs/sample

spring:
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 2000
    database: 0

    # redis 线程池配置
    pool:
      #redis的最大分配对象#
      max-total: 1024
      #redis最大保存idel状态对象数 #
      max-idle: 20
      #redis最小保存idel状态对象数 #
      min-idle: 10
      #redis池没有对象返回时，最大等待时间 #
      max-wait-millis: 10000
      test-on-borrow: true
      test-on-return: true

  # 系统语言如果不设置，则根据浏览器切换
  mvc:
    locale:

#### jdbc config ####################################################################################
datasource:
  # 使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/zom_sample?autoReconnect:true&characterEncoding=UTF-8
  username: root
  password: root

  #连接池配置(druid补充)
  # 初始化大小，最小，最大
  initialSize: 5
  minIdle: 5
  maxActive: 1000
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  #建议配置为true，不影响性能，并且保证安全性。
  testWhileIdle: true
  #申请连接时执行validationQuery检测连接是否有效
  testOnBorrow: false
  #归还连接时执行validationQuery检测连接是否有效
  testOnReturn: false
  #是否缓存preparedStatement，也就是PSCache。
  #PSCache对支持游标的数据库性能提升巨大，比如说oracle。
  #在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。
  #5.5及以上版本有PSCache，建议开启。
  poolPreparedStatements: true
  #要启用PSCache，必须配置大于0，当大于0时，
  #poolPreparedStatements自动触发修改为true。
  #在Druid中，不会存在Oracle下PSCache占用内存过多的问题，
  #可以把这个数值配置大一些，比如说100
  maxOpenPreparedStatements: 100
  maxPoolPreparedStatementPerConnectionSize: 20
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: stat,wall
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
  # 合并多个DruidDataSource的监控数据
  #    useGlobalDataSourceStat: true

  #打开连接检查功能，30分钟不使用的连接将被收回，并记录日志（用于测试没有关闭连接的代码）
  removeAbandoned: true
  removeAbandonedTimeout: 1800
  logAbandoned: true



